[package]
name = "phonnz-back"
authors = ["phonnz <gonzalezm.alfonso@gmail.com>"]
description = ""
version = "0.1.0"
edition = "2021"


[dependencies]
yew = { version = "0.20", features = ["csr"] }

[workspace]
