spin_manifest_version = "1"
authors = ["phonnz <gonzalezm.alfonso@gmail.com>"]
description = ""
name = "phonnz-back"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "phonnz-back"
source = "target/wasm32-wasi/release/phonnz_back.wasm"
#key_value_stores = ["main"]
allowed_http_hosts = []
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
id = "ui"
files = [ { source = "assets", destination = "/" } ]
[component.trigger]
route = "/..."

