spin_manifest_version = 2

[application]
name = "phonnz-back"
version = "0.1.0"
authors = ["phonnz <gonzalezm.alfonso@gmail.com>"]

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-phonnz-back"
component = "phonnz-back"
route = "/api/..."

[[trigger.http]]
id = "trigger-ui"
component = "ui"
route = "/..."

[component.phonnz-back]
source = "target/wasm32-wasi/release/phonnz_back.wasm"
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]

[component.phonnz-back.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.ui]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
files = [{ source = "assets", destination = "/" }]
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
